describe('orchestrator', () => {
  it('VALID: exports module', async () => {
    const orchestrator = await import('./index');

    const exportedKeys = Object.keys(orchestrator).sort();

    expect(exportedKeys).toStrictEqual([
      'StartOrchestrator',
      'addQuestInputContract',
      'addQuestResultContract',
      'agentPromptResultContract',
      'agentRoleContract',
      'agentSlotContract',
      'chaoswhispererPromptStatics',
      'codeweaverPromptStatics',
      'followupDepthContract',
      'getQuestInputContract',
      'getQuestResultContract',
      'isoTimestampContract',
      'lawbringerPromptStatics',
      'modifyQuestInputContract',
      'modifyQuestResultContract',
      'orchestrationEventsState',
      'orchestrationProcessesState',
      'pathseekerPromptStatics',
      'questAddBroker',
      'questFindQuestPathBroker',
      'questFolderFindBroker',
      'questGetBroker',
      'questListBroker',
      'questLoadBroker',
      'questModifyBroker',
      'questOutboxWatchBroker',
      'questSectionContract',
      'questStageContract',
      'questValidateSpecBroker',
      'questVerifyBroker',
      'sessionIdExtractorTransformer',
      'siegemasterPromptStatics',
      'signalFromStreamTransformer',
      'slotCountContract',
      'slotDataContract',
      'slotIndexContract',
      'slotManagerResultContract',
      'slotOperationsContract',
      'spiritmenderPromptStatics',
      'streamJsonLineContract',
      'streamJsonToTextTransformer',
      'streamJsonToToolUseTransformer',
      'streamSignalContract',
      'toolDisplayConfigStatics',
      'toolInputToDisplayTransformer',
      'validateSpecInputContract',
      'verifyQuestCheckContract',
      'verifyQuestInputContract',
      'verifyQuestResultContract',
      'workItemIdContract',
      'workTrackerContract',
    ]);
  });
});
