import { bannedQueryMethodsStatics } from './banned-query-methods-statics';

describe('bannedQueryMethodsStatics', () => {
  it('VALID: exported value => matches expected shape', () => {
    expect(bannedQueryMethodsStatics).toStrictEqual({
      prefixes: ['get', 'getAll', 'query', 'queryAll', 'find', 'findAll'],
      bannedSuffixes: [
        'ByText',
        'ByAltText',
        'ByTitle',
        'ByPlaceholderText',
        'ByDisplayValue',
        'ByLabelText',
      ],
      screenMethods: [
        'getByText',
        'getByAltText',
        'getByTitle',
        'getByPlaceholderText',
        'getByDisplayValue',
        'getByLabelText',
        'getAllByText',
        'getAllByAltText',
        'getAllByTitle',
        'getAllByPlaceholderText',
        'getAllByDisplayValue',
        'getAllByLabelText',
        'queryByText',
        'queryByAltText',
        'queryByTitle',
        'queryByPlaceholderText',
        'queryByDisplayValue',
        'queryByLabelText',
        'queryAllByText',
        'queryAllByAltText',
        'queryAllByTitle',
        'queryAllByPlaceholderText',
        'queryAllByDisplayValue',
        'queryAllByLabelText',
        'findByText',
        'findByAltText',
        'findByTitle',
        'findByPlaceholderText',
        'findByDisplayValue',
        'findByLabelText',
        'findAllByText',
        'findAllByAltText',
        'findAllByTitle',
        'findAllByPlaceholderText',
        'findAllByDisplayValue',
        'findAllByLabelText',
      ],
      screenMethodSet: new Set([
        'getByText',
        'getByAltText',
        'getByTitle',
        'getByPlaceholderText',
        'getByDisplayValue',
        'getByLabelText',
        'getAllByText',
        'getAllByAltText',
        'getAllByTitle',
        'getAllByPlaceholderText',
        'getAllByDisplayValue',
        'getAllByLabelText',
        'queryByText',
        'queryByAltText',
        'queryByTitle',
        'queryByPlaceholderText',
        'queryByDisplayValue',
        'queryByLabelText',
        'queryAllByText',
        'queryAllByAltText',
        'queryAllByTitle',
        'queryAllByPlaceholderText',
        'queryAllByDisplayValue',
        'queryAllByLabelText',
        'findByText',
        'findByAltText',
        'findByTitle',
        'findByPlaceholderText',
        'findByDisplayValue',
        'findByLabelText',
        'findAllByText',
        'findAllByAltText',
        'findAllByTitle',
        'findAllByPlaceholderText',
        'findAllByDisplayValue',
        'findAllByLabelText',
      ]),
      replacementRecord: {
        getByText: 'getByTestId',
        getByAltText: 'getByTestId',
        getByTitle: 'getByTestId',
        getByPlaceholderText: 'getByTestId',
        getByDisplayValue: 'getByTestId',
        getByLabelText: 'getByTestId',
        getAllByText: 'getAllByTestId',
        getAllByAltText: 'getAllByTestId',
        getAllByTitle: 'getAllByTestId',
        getAllByPlaceholderText: 'getAllByTestId',
        getAllByDisplayValue: 'getAllByTestId',
        getAllByLabelText: 'getAllByTestId',
        queryByText: 'queryByTestId',
        queryByAltText: 'queryByTestId',
        queryByTitle: 'queryByTestId',
        queryByPlaceholderText: 'queryByTestId',
        queryByDisplayValue: 'queryByTestId',
        queryByLabelText: 'queryByTestId',
        queryAllByText: 'queryAllByTestId',
        queryAllByAltText: 'queryAllByTestId',
        queryAllByTitle: 'queryAllByTestId',
        queryAllByPlaceholderText: 'queryAllByTestId',
        queryAllByDisplayValue: 'queryAllByTestId',
        queryAllByLabelText: 'queryAllByTestId',
        findByText: 'findByTestId',
        findByAltText: 'findByTestId',
        findByTitle: 'findByTestId',
        findByPlaceholderText: 'findByTestId',
        findByDisplayValue: 'findByTestId',
        findByLabelText: 'findByTestId',
        findAllByText: 'findAllByTestId',
        findAllByAltText: 'findAllByTestId',
        findAllByTitle: 'findAllByTestId',
        findAllByPlaceholderText: 'findAllByTestId',
        findAllByDisplayValue: 'findAllByTestId',
        findAllByLabelText: 'findAllByTestId',
      },
      containerMethods: ['querySelector', 'querySelectorAll'],
      containerMethodSet: new Set(['querySelector', 'querySelectorAll']),
    });
  });
});
