import { frameworkPresetsDataStatics } from './framework-presets-data-statics';

describe('frameworkPresetsDataStatics', () => {
  it('VALID: exported value => matches expected shape', () => {
    expect(frameworkPresetsDataStatics).toStrictEqual({
      presets: {
        react: {
          widgets: ['react', 'react-dom'],
          bindings: ['react', 'react-dom'],
          state: ['react', 'react-dom'],
          flows: [],
          responders: [],
          contracts: [],
          brokers: [],
          transformers: [],
          errors: [],
          middleware: [],
          adapters: ['*'],
          startup: ['*'],
        },
        vue: {
          widgets: ['vue'],
          bindings: ['vue'],
          state: ['vue'],
          flows: [],
          responders: [],
          contracts: [],
          brokers: [],
          transformers: [],
          errors: [],
          middleware: [],
          adapters: ['*'],
          startup: ['*'],
        },
        angular: {
          widgets: ['@angular/core', '@angular/common'],
          bindings: ['@angular/core', '@angular/common'],
          state: ['@angular/core', '@angular/common'],
          flows: [],
          responders: [],
          contracts: [],
          brokers: [],
          transformers: [],
          errors: [],
          middleware: [],
          adapters: ['*'],
          startup: ['*'],
        },
        svelte: {
          widgets: ['svelte'],
          bindings: ['svelte'],
          state: ['svelte'],
          flows: [],
          responders: [],
          contracts: [],
          brokers: [],
          transformers: [],
          errors: [],
          middleware: [],
          adapters: ['*'],
          startup: ['*'],
        },
        solid: {
          widgets: ['solid-js'],
          bindings: ['solid-js'],
          state: ['solid-js'],
          flows: [],
          responders: [],
          contracts: [],
          brokers: [],
          transformers: [],
          errors: [],
          middleware: [],
          adapters: ['*'],
          startup: ['*'],
        },
        preact: {
          widgets: ['preact'],
          bindings: ['preact'],
          state: ['preact'],
          flows: [],
          responders: [],
          contracts: [],
          brokers: [],
          transformers: [],
          errors: [],
          middleware: [],
          adapters: ['*'],
          startup: ['*'],
        },
        express: {
          widgets: null,
          bindings: null,
          state: [],
          flows: ['express'],
          responders: [],
          contracts: [],
          brokers: [],
          transformers: [],
          errors: [],
          middleware: [],
          adapters: ['*'],
          startup: ['*'],
        },
        fastify: {
          widgets: null,
          bindings: null,
          state: [],
          flows: ['fastify'],
          responders: [],
          contracts: [],
          brokers: [],
          transformers: [],
          errors: [],
          middleware: [],
          adapters: ['*'],
          startup: ['*'],
        },
        koa: {
          widgets: null,
          bindings: null,
          state: [],
          flows: ['koa', '@koa/router'],
          responders: [],
          contracts: [],
          brokers: [],
          transformers: [],
          errors: [],
          middleware: [],
          adapters: ['*'],
          startup: ['*'],
        },
        hapi: {
          widgets: null,
          bindings: null,
          state: [],
          flows: ['@hapi/hapi'],
          responders: [],
          contracts: [],
          brokers: [],
          transformers: [],
          errors: [],
          middleware: [],
          adapters: ['*'],
          startup: ['*'],
        },
        nestjs: {
          widgets: null,
          bindings: null,
          state: [],
          flows: ['@nestjs/core', '@nestjs/common'],
          responders: [],
          contracts: [],
          brokers: [],
          transformers: [],
          errors: [],
          middleware: [],
          adapters: ['*'],
          startup: ['*'],
        },
        nextjs: {
          widgets: ['react', 'react-dom', 'next'],
          bindings: ['react', 'react-dom', 'next'],
          state: ['react', 'react-dom', 'next'],
          flows: ['next'],
          responders: [],
          contracts: [],
          brokers: [],
          transformers: [],
          errors: [],
          middleware: [],
          adapters: ['*'],
          startup: ['*'],
        },
        nuxtjs: {
          widgets: ['vue', 'nuxt'],
          bindings: ['vue', 'nuxt'],
          state: ['vue', 'nuxt'],
          flows: ['nuxt'],
          responders: [],
          contracts: [],
          brokers: [],
          transformers: [],
          errors: [],
          middleware: [],
          adapters: ['*'],
          startup: ['*'],
        },
        remix: {
          widgets: ['react', 'react-dom', '@remix-run/react'],
          bindings: ['react', 'react-dom', '@remix-run/react'],
          state: ['react', 'react-dom', '@remix-run/react'],
          flows: ['@remix-run/react'],
          responders: [],
          contracts: [],
          brokers: [],
          transformers: [],
          errors: [],
          middleware: [],
          adapters: ['*'],
          startup: ['*'],
        },
        'node-library': {
          widgets: null,
          bindings: null,
          state: [],
          flows: null,
          responders: null,
          contracts: [],
          brokers: [],
          transformers: [],
          errors: [],
          middleware: [],
          adapters: ['*'],
          startup: ['*'],
        },
        'react-library': {
          widgets: ['react', 'react-dom'],
          bindings: ['react', 'react-dom'],
          state: ['react', 'react-dom'],
          flows: null,
          responders: null,
          contracts: [],
          brokers: [],
          transformers: [],
          errors: [],
          middleware: [],
          adapters: ['*'],
          startup: ['*'],
        },
        cli: {
          widgets: null,
          bindings: null,
          state: [],
          flows: null,
          responders: null,
          contracts: [],
          brokers: [],
          transformers: [],
          errors: [],
          middleware: [],
          adapters: ['*'],
          startup: ['*'],
        },
        'ink-cli': {
          widgets: ['ink', 'react'],
          bindings: ['ink', 'react'],
          state: ['ink', 'react'],
          flows: null,
          responders: null,
          contracts: [],
          brokers: [],
          transformers: [],
          errors: [],
          middleware: [],
          adapters: ['*'],
          startup: ['*'],
        },
        monorepo: {
          widgets: null,
          bindings: null,
          state: null,
          flows: null,
          responders: null,
          contracts: [],
          brokers: [],
          transformers: [],
          errors: [],
          middleware: [],
          adapters: ['*'],
          startup: ['*'],
        },
      },
    });
  });
});
