/**
 * PURPOSE: Catalog of smoketest case definitions per suite — single-agent cases for mcp/signals each point at a prompt key; orchestration cases reference full scenarios from smoketestScenariosStatics
 *
 * USAGE:
 * smoketestCaseCatalogStatics.mcp;
 * // Returns: readonly tuple of single-agent cases (one per MCP tool exercised by the suite) — { caseId, name, promptKey }
 * smoketestCaseCatalogStatics.orchestration;
 * // Returns: readonly tuple of full scenarios from smoketestScenariosStatics — { caseId, name, blueprint, scripts, assertions, ... }
 *
 * DYNAMIC GENERATION: The `mcp` suite is synthesized from `mcpToolsStatics.tools.names` — one case per
 * registered MCP tool, except tools whose probe-args entry is flagged `mode: 'skip-from-suite'`. Those
 * tools (e.g. `start-quest`) are exercised by the orchestration suite instead. Case IDs follow
 * `mcp-${toolName}`, display names follow `MCP: ${toolName}`, and `promptKey` is the tool name itself
 * (matching the keys generated by `smoketestPromptsStatics`).
 *
 * WHEN-TO-USE: SmoketestRunResponder dispatches on suite; orchestration entries go through smoketestRunCaseBroker.
 * mcp/signals entries are bundled via caseCatalogToBlueprintTransformer into a single blueprint per suite (Phase 7).
 */

import { mcpToolsStatics } from '@dungeonmaster/shared/statics';

import { smoketestProbeArgsStatics } from '../smoketest-probe-args/smoketest-probe-args-statics';
import { smoketestScenariosStatics } from '../smoketest-scenarios/smoketest-scenarios-statics';

const mcpCases = mcpToolsStatics.tools.names.flatMap((toolName) => {
  if (smoketestProbeArgsStatics[toolName].mode === 'skip-from-suite') {
    return [];
  }
  return [
    {
      caseId: `mcp-${toolName}`,
      name: `MCP: ${toolName}`,
      promptKey: toolName,
      expectedSignal: 'complete',
    } as const,
  ];
});

export const smoketestCaseCatalogStatics = {
  mcp: mcpCases,
  signals: [
    {
      caseId: 'signal-complete',
      name: 'Signal: complete',
      promptKey: 'signalComplete',
      expectedSignal: 'complete',
    },
    {
      caseId: 'signal-failed',
      name: 'Signal: failed',
      promptKey: 'signalFailed',
      expectedSignal: 'failed',
    },
    {
      caseId: 'signal-failed-replan',
      name: 'Signal: failed-replan',
      promptKey: 'signalFailedReplan',
      expectedSignal: 'failed-replan',
    },
  ],
  orchestration: [
    smoketestScenariosStatics.orchHappyPath,
    smoketestScenariosStatics.orchCodeweaverFail,
    smoketestScenariosStatics.orchLawbringerFail,
    smoketestScenariosStatics.orchDepthExhaustion,
    smoketestScenariosStatics.orchBlightwardenReplan,
  ],
} as const;
