/**
 * PURPOSE: Maps quest statuses to their visible spec panel sections and header labels
 *
 * USAGE:
 * questGateSectionsStatics.sections['flows_approved'];
 * // Returns ['flows', 'designDecisions', 'contracts', 'toolingRequirements']
 */

export const questGateSectionsStatics = {
  sections: {
    created: ['flows', 'designDecisions'],
    pending: ['flows', 'designDecisions'],
    explore_flows: ['flows', 'designDecisions'],
    review_flows: ['flows', 'designDecisions'],
    flows_approved: ['flows', 'designDecisions', 'contracts', 'toolingRequirements'],
    explore_observables: ['flows', 'designDecisions', 'contracts', 'toolingRequirements'],
    review_observables: ['flows', 'designDecisions', 'contracts', 'toolingRequirements'],
    approved: ['flows', 'designDecisions', 'contracts', 'toolingRequirements'],
    explore_design: ['flows', 'designDecisions', 'contracts', 'toolingRequirements'],
    review_design: ['flows', 'designDecisions', 'contracts', 'toolingRequirements'],
    design_approved: ['flows', 'designDecisions', 'contracts', 'toolingRequirements'],
    seek_scope: ['flows', 'designDecisions', 'contracts', 'toolingRequirements'],
    seek_synth: ['flows', 'designDecisions', 'contracts', 'toolingRequirements'],
    seek_walk: ['flows', 'designDecisions', 'contracts', 'toolingRequirements'],
    seek_plan: ['flows', 'designDecisions', 'contracts', 'toolingRequirements'],
    in_progress: ['flows', 'designDecisions', 'contracts', 'toolingRequirements'],
    paused: ['flows', 'designDecisions', 'contracts', 'toolingRequirements'],
    blocked: ['flows', 'designDecisions', 'contracts', 'toolingRequirements'],
    complete: ['flows', 'designDecisions', 'contracts', 'toolingRequirements'],
    abandoned: ['flows', 'designDecisions', 'contracts', 'toolingRequirements'],
  },
  headers: {
    created: 'QUEST CREATED',
    pending: 'QUEST CREATED',
    explore_flows: 'EXPLORING FLOWS',
    review_flows: 'FLOW APPROVAL',
    flows_approved: 'FLOWS APPROVED',
    explore_observables: 'EXPLORING OBSERVABLES',
    review_observables: 'OBSERVABLES APPROVAL',
    approved: 'SPEC APPROVED',
    explore_design: 'EXPLORING DESIGN',
    review_design: 'DESIGN APPROVAL',
    design_approved: 'DESIGN APPROVED',
    seek_scope: 'SEEK SCOPE',
    seek_synth: 'SEEK SYNTH',
    seek_walk: 'SEEK WALK',
    seek_plan: 'SEEK PLAN',
    in_progress: 'IN PROGRESS',
    paused: 'EXECUTION PAUSED',
    blocked: 'EXECUTION BLOCKED',
    complete: 'EXECUTION COMPLETE',
    abandoned: 'ABANDONED',
  },
  nextApprovalStatus: {
    created: null,
    pending: null,
    explore_flows: null,
    review_flows: 'flows_approved',
    flows_approved: null,
    explore_observables: null,
    review_observables: 'approved',
    approved: null,
    explore_design: null,
    review_design: 'design_approved',
    design_approved: null,
    seek_scope: null,
    seek_synth: null,
    seek_walk: null,
    seek_plan: null,
    in_progress: null,
    paused: null,
    blocked: null,
    complete: null,
    abandoned: null,
  },
} as const;
