import { registerSpyOn } from '@dungeonmaster/testing/register-mock';
import { AbsoluteFilePathStub } from '@dungeonmaster/shared/contracts';

import { runIdMockStatics } from '../../../statics/run-id-mock/run-id-mock-statics';
import { runIdGenerateTransformer } from '../../../transformers/run-id-generate/run-id-generate-transformer';
import type { ProjectFolder } from '../../../contracts/project-folder/project-folder-contract';
import { checkRunLintBrokerProxy } from '../../check-run/lint/check-run-lint-broker.proxy';
import { checkRunTypecheckBrokerProxy } from '../../check-run/typecheck/check-run-typecheck-broker.proxy';
import { checkRunUnitBrokerProxy } from '../../check-run/unit/check-run-unit-broker.proxy';
import { checkRunIntegrationBrokerProxy } from '../../check-run/integration/check-run-integration-broker.proxy';
import { checkRunE2eBrokerProxy } from '../../check-run/e2e/check-run-e2e-broker.proxy';
import { storageSaveBrokerProxy } from '../../storage/save/storage-save-broker.proxy';
import { storagePruneBrokerProxy } from '../../storage/prune/storage-prune-broker.proxy';

export const commandRunLayerSingleBrokerProxy = (): {
  setupAllChecksPass: (params: { projectFolder: ProjectFolder }) => void;
  setupLintOnlyPass: (params: { projectFolder: ProjectFolder }) => void;
  setupLintOnlyFail: (params: { projectFolder: ProjectFolder; stdout: string }) => void;
  setupE2eOnlySkip: (params: { projectFolder: ProjectFolder }) => void;
  getStderrCalls: () => unknown[];
} => {
  // Date.now/Math.random take no identifying argument — the receiver is what a spy cannot see.
  registerSpyOn({ object: Date, method: 'now' }).calledWith([]).returns(runIdMockStatics.timestamp);
  registerSpyOn({ object: Math, method: 'random' })
    .calledWith([])
    .returns(runIdMockStatics.randomValue);
  // write()'s return value never varies by content — what was written is read back via
  // callsMatching below, so the catch-all stays unaddressed.
  const stderrSpy = registerSpyOn({ object: process.stderr, method: 'write' });
  stderrSpy.calledWith([]).returns(true);

  const lintProxy = checkRunLintBrokerProxy();
  const typecheckProxy = checkRunTypecheckBrokerProxy();
  const unitProxy = checkRunUnitBrokerProxy();
  const integrationProxy = checkRunIntegrationBrokerProxy();
  const e2eProxy = checkRunE2eBrokerProxy();
  const saveProxy = storageSaveBrokerProxy();
  const pruneProxy = storagePruneBrokerProxy();

  // Both callers of this proxy (command-run-layer-single-broker.test.ts directly, and
  // command-run-broker.proxy.ts via the single-package path) save/prune against rootPath
  // '/project'. The runId is generated by the real transformer, reading the Date/Math spies staged
  // above — the identical deterministic value the broker under test will generate.
  const rootPath = AbsoluteFilePathStub({ value: '/project' });
  const runId = runIdGenerateTransformer();

  return {
    setupAllChecksPass: ({ projectFolder }: { projectFolder: ProjectFolder }): void => {
      lintProxy.setupPass({ projectFolder });
      typecheckProxy.setupPass({ projectFolder });
      unitProxy.setupPass({ projectFolder });
      integrationProxy.setupPass({ projectFolder });
      e2eProxy.setupPass({ projectFolder });
      saveProxy.setupSuccess({ rootPath, runId });
      pruneProxy.setupEmpty({ rootPath });
    },
    setupLintOnlyPass: ({ projectFolder }: { projectFolder: ProjectFolder }): void => {
      lintProxy.setupPass({ projectFolder });
      saveProxy.setupSuccess({ rootPath, runId });
      pruneProxy.setupEmpty({ rootPath });
    },
    setupLintOnlyFail: ({
      projectFolder,
      stdout,
    }: {
      projectFolder: ProjectFolder;
      stdout: string;
    }): void => {
      lintProxy.setupFail({ projectFolder, stdout });
      saveProxy.setupSuccess({ rootPath, runId });
      pruneProxy.setupEmpty({ rootPath });
    },
    setupE2eOnlySkip: ({ projectFolder }: { projectFolder: ProjectFolder }): void => {
      e2eProxy.setupNoPlaywrightConfig({ projectFolder });
      saveProxy.setupSuccess({ rootPath, runId });
      pruneProxy.setupEmpty({ rootPath });
    },
    getStderrCalls: (): unknown[] => stderrSpy.callsMatching([]).map((call) => call[0]),
  };
};
