/**
 * PURPOSE: Per-quest-status metadata record — source of truth for every quest-status flag and derived value
 *
 * USAGE:
 * questStatusMetadataStatics.statuses.in_progress;
 * // Returns { isActivelyExecuting: true, isPauseable: true, ... , displayHeader: 'IN PROGRESS' }
 */

export const questStatusMetadataStatics = {
  statuses: {
    created: {
      isPreExecution: true,
      isPathseekerRunning: false,
      isAnyAgentRunning: false,
      isActivelyExecuting: false,
      isUserPaused: false,
      isQuestBlocked: false,
      isTerminal: false,
      isPauseable: false,
      isResumable: false,
      isStartable: false,
      isRecoverable: true,
      isAutoResumable: false,
      isGateApproved: false,
      isDesignPhase: false,
      isAbandonable: true,
      shouldRenderExecutionPanel: false,
      nextApprovalStatus: null,
      previousReviewStatus: null,
      displayHeader: 'QUEST CREATED',
    },
    pending: {
      isPreExecution: true,
      isPathseekerRunning: false,
      isAnyAgentRunning: false,
      isActivelyExecuting: false,
      isUserPaused: false,
      isQuestBlocked: false,
      isTerminal: false,
      isPauseable: false,
      isResumable: false,
      isStartable: false,
      isRecoverable: true,
      isAutoResumable: false,
      isGateApproved: false,
      isDesignPhase: false,
      isAbandonable: true,
      shouldRenderExecutionPanel: false,
      nextApprovalStatus: null,
      previousReviewStatus: null,
      displayHeader: 'QUEST CREATED',
    },
    explore_flows: {
      isPreExecution: true,
      isPathseekerRunning: false,
      isAnyAgentRunning: false,
      isActivelyExecuting: false,
      isUserPaused: false,
      isQuestBlocked: false,
      isTerminal: false,
      isPauseable: false,
      isResumable: false,
      isStartable: false,
      isRecoverable: true,
      isAutoResumable: false,
      isGateApproved: false,
      isDesignPhase: false,
      isAbandonable: true,
      shouldRenderExecutionPanel: false,
      nextApprovalStatus: null,
      previousReviewStatus: null,
      displayHeader: 'EXPLORING FLOWS',
    },
    review_flows: {
      isPreExecution: true,
      isPathseekerRunning: false,
      isAnyAgentRunning: false,
      isActivelyExecuting: false,
      isUserPaused: false,
      isQuestBlocked: false,
      isTerminal: false,
      isPauseable: false,
      isResumable: false,
      isStartable: false,
      isRecoverable: false,
      isAutoResumable: false,
      isGateApproved: false,
      isDesignPhase: false,
      isAbandonable: true,
      shouldRenderExecutionPanel: false,
      nextApprovalStatus: 'flows_approved',
      previousReviewStatus: null,
      displayHeader: 'FLOW APPROVAL',
    },
    flows_approved: {
      isPreExecution: true,
      isPathseekerRunning: false,
      isAnyAgentRunning: false,
      isActivelyExecuting: false,
      isUserPaused: false,
      isQuestBlocked: false,
      isTerminal: false,
      isPauseable: false,
      isResumable: false,
      isStartable: false,
      isRecoverable: true,
      isAutoResumable: false,
      isGateApproved: true,
      isDesignPhase: false,
      isAbandonable: true,
      shouldRenderExecutionPanel: false,
      nextApprovalStatus: null,
      previousReviewStatus: 'review_flows',
      displayHeader: 'FLOWS APPROVED',
    },
    explore_observables: {
      isPreExecution: true,
      isPathseekerRunning: false,
      isAnyAgentRunning: false,
      isActivelyExecuting: false,
      isUserPaused: false,
      isQuestBlocked: false,
      isTerminal: false,
      isPauseable: false,
      isResumable: false,
      isStartable: false,
      isRecoverable: true,
      isAutoResumable: false,
      isGateApproved: false,
      isDesignPhase: false,
      isAbandonable: true,
      shouldRenderExecutionPanel: false,
      nextApprovalStatus: null,
      previousReviewStatus: null,
      displayHeader: 'EXPLORING OBSERVABLES',
    },
    review_observables: {
      isPreExecution: true,
      isPathseekerRunning: false,
      isAnyAgentRunning: false,
      isActivelyExecuting: false,
      isUserPaused: false,
      isQuestBlocked: false,
      isTerminal: false,
      isPauseable: false,
      isResumable: false,
      isStartable: false,
      isRecoverable: false,
      isAutoResumable: false,
      isGateApproved: false,
      isDesignPhase: false,
      isAbandonable: true,
      shouldRenderExecutionPanel: false,
      nextApprovalStatus: 'approved',
      previousReviewStatus: null,
      displayHeader: 'OBSERVABLES APPROVAL',
    },
    approved: {
      isPreExecution: true,
      isPathseekerRunning: false,
      isAnyAgentRunning: false,
      isActivelyExecuting: false,
      isUserPaused: false,
      isQuestBlocked: false,
      isTerminal: false,
      isPauseable: false,
      isResumable: false,
      isStartable: true,
      isRecoverable: false,
      isAutoResumable: false,
      isGateApproved: true,
      isDesignPhase: false,
      isAbandonable: true,
      shouldRenderExecutionPanel: false,
      nextApprovalStatus: null,
      previousReviewStatus: 'review_observables',
      displayHeader: 'SPEC APPROVED',
    },
    explore_design: {
      isPreExecution: true,
      isPathseekerRunning: false,
      isAnyAgentRunning: false,
      isActivelyExecuting: false,
      isUserPaused: false,
      isQuestBlocked: false,
      isTerminal: false,
      isPauseable: false,
      isResumable: false,
      isStartable: false,
      isRecoverable: true,
      isAutoResumable: false,
      isGateApproved: false,
      isDesignPhase: true,
      isAbandonable: true,
      shouldRenderExecutionPanel: false,
      nextApprovalStatus: null,
      previousReviewStatus: null,
      displayHeader: 'EXPLORING DESIGN',
    },
    review_design: {
      isPreExecution: true,
      isPathseekerRunning: false,
      isAnyAgentRunning: false,
      isActivelyExecuting: false,
      isUserPaused: false,
      isQuestBlocked: false,
      isTerminal: false,
      isPauseable: false,
      isResumable: false,
      isStartable: false,
      isRecoverable: false,
      isAutoResumable: false,
      isGateApproved: false,
      isDesignPhase: true,
      isAbandonable: true,
      shouldRenderExecutionPanel: false,
      nextApprovalStatus: 'design_approved',
      previousReviewStatus: null,
      displayHeader: 'DESIGN APPROVAL',
    },
    design_approved: {
      isPreExecution: true,
      isPathseekerRunning: false,
      isAnyAgentRunning: false,
      isActivelyExecuting: false,
      isUserPaused: false,
      isQuestBlocked: false,
      isTerminal: false,
      isPauseable: false,
      isResumable: false,
      isStartable: true,
      isRecoverable: false,
      isAutoResumable: false,
      isGateApproved: true,
      isDesignPhase: true,
      isAbandonable: true,
      shouldRenderExecutionPanel: false,
      nextApprovalStatus: null,
      previousReviewStatus: 'review_design',
      displayHeader: 'DESIGN APPROVED',
    },
    seek_scope: {
      isPreExecution: false,
      isPathseekerRunning: true,
      isAnyAgentRunning: true,
      isActivelyExecuting: false,
      isUserPaused: false,
      isQuestBlocked: false,
      isTerminal: false,
      isPauseable: true,
      isResumable: false,
      isStartable: false,
      isRecoverable: true,
      isAutoResumable: false,
      isGateApproved: false,
      isDesignPhase: false,
      isAbandonable: true,
      shouldRenderExecutionPanel: true,
      nextApprovalStatus: null,
      previousReviewStatus: null,
      displayHeader: 'SEEK SCOPE',
    },
    seek_synth: {
      isPreExecution: false,
      isPathseekerRunning: true,
      isAnyAgentRunning: true,
      isActivelyExecuting: false,
      isUserPaused: false,
      isQuestBlocked: false,
      isTerminal: false,
      isPauseable: true,
      isResumable: false,
      isStartable: false,
      isRecoverable: true,
      isAutoResumable: false,
      isGateApproved: false,
      isDesignPhase: false,
      isAbandonable: true,
      shouldRenderExecutionPanel: true,
      nextApprovalStatus: null,
      previousReviewStatus: null,
      displayHeader: 'SEEK SYNTH',
    },
    seek_walk: {
      isPreExecution: false,
      isPathseekerRunning: true,
      isAnyAgentRunning: true,
      isActivelyExecuting: false,
      isUserPaused: false,
      isQuestBlocked: false,
      isTerminal: false,
      isPauseable: true,
      isResumable: false,
      isStartable: false,
      isRecoverable: true,
      isAutoResumable: false,
      isGateApproved: false,
      isDesignPhase: false,
      isAbandonable: true,
      shouldRenderExecutionPanel: true,
      nextApprovalStatus: null,
      previousReviewStatus: null,
      displayHeader: 'SEEK WALK',
    },
    seek_plan: {
      isPreExecution: false,
      isPathseekerRunning: true,
      isAnyAgentRunning: true,
      isActivelyExecuting: false,
      isUserPaused: false,
      isQuestBlocked: false,
      isTerminal: false,
      isPauseable: true,
      isResumable: false,
      isStartable: false,
      isRecoverable: true,
      isAutoResumable: false,
      isGateApproved: false,
      isDesignPhase: false,
      isAbandonable: true,
      shouldRenderExecutionPanel: true,
      nextApprovalStatus: null,
      previousReviewStatus: null,
      displayHeader: 'SEEK PLAN',
    },
    in_progress: {
      isPreExecution: false,
      isPathseekerRunning: false,
      isAnyAgentRunning: true,
      isActivelyExecuting: true,
      isUserPaused: false,
      isQuestBlocked: false,
      isTerminal: false,
      isPauseable: true,
      isResumable: false,
      isStartable: false,
      isRecoverable: true,
      isAutoResumable: true,
      isGateApproved: false,
      isDesignPhase: false,
      isAbandonable: true,
      shouldRenderExecutionPanel: true,
      nextApprovalStatus: null,
      previousReviewStatus: null,
      displayHeader: 'IN PROGRESS',
    },
    paused: {
      isPreExecution: false,
      isPathseekerRunning: false,
      isAnyAgentRunning: false,
      isActivelyExecuting: false,
      isUserPaused: true,
      isQuestBlocked: false,
      isTerminal: false,
      isPauseable: false,
      isResumable: true,
      isStartable: false,
      isRecoverable: false,
      isAutoResumable: false,
      isGateApproved: false,
      isDesignPhase: false,
      isAbandonable: true,
      shouldRenderExecutionPanel: true,
      nextApprovalStatus: null,
      previousReviewStatus: null,
      displayHeader: 'EXECUTION PAUSED',
    },
    blocked: {
      isPreExecution: false,
      isPathseekerRunning: false,
      isAnyAgentRunning: false,
      isActivelyExecuting: false,
      isUserPaused: false,
      isQuestBlocked: true,
      isTerminal: false,
      isPauseable: false,
      isResumable: true,
      isStartable: false,
      isRecoverable: false,
      isAutoResumable: false,
      isGateApproved: false,
      isDesignPhase: false,
      isAbandonable: true,
      shouldRenderExecutionPanel: true,
      nextApprovalStatus: null,
      previousReviewStatus: null,
      displayHeader: 'EXECUTION BLOCKED',
    },
    complete: {
      isPreExecution: false,
      isPathseekerRunning: false,
      isAnyAgentRunning: false,
      isActivelyExecuting: false,
      isUserPaused: false,
      isQuestBlocked: false,
      isTerminal: true,
      isPauseable: false,
      isResumable: false,
      isStartable: false,
      isRecoverable: false,
      isAutoResumable: false,
      isGateApproved: false,
      isDesignPhase: false,
      isAbandonable: false,
      shouldRenderExecutionPanel: true,
      nextApprovalStatus: null,
      previousReviewStatus: null,
      displayHeader: 'EXECUTION COMPLETE',
    },
    abandoned: {
      isPreExecution: false,
      isPathseekerRunning: false,
      isAnyAgentRunning: false,
      isActivelyExecuting: false,
      isUserPaused: false,
      isQuestBlocked: false,
      isTerminal: true,
      isPauseable: false,
      isResumable: false,
      isStartable: false,
      isRecoverable: false,
      isAutoResumable: false,
      isGateApproved: false,
      isDesignPhase: false,
      isAbandonable: false,
      shouldRenderExecutionPanel: true,
      nextApprovalStatus: null,
      previousReviewStatus: null,
      displayHeader: 'ABANDONED',
    },
  },
} as const;
