import { zodObjectBrandStatics } from './zod-object-brand-statics';

describe('zodObjectBrandStatics', () => {
  it('VALID: {} => holds the method names the brand rule sorts a chain by', () => {
    expect(zodObjectBrandStatics).toStrictEqual({
      objectRoots: ['object', 'strictObject', 'looseObject'],
      deriveMethods: ['extend', 'pick', 'omit', 'partial', 'required', 'merge', 'safeExtend'],
      objectLevelMethods: [
        'extend',
        'pick',
        'omit',
        'partial',
        'required',
        'merge',
        'safeExtend',
        'strict',
        'passthrough',
        'strip',
        'catchall',
      ],
      unbrandableRoots: ['enum', 'nativeEnum', 'literal', 'boolean'],
      leafRoots: [
        'string',
        'number',
        'int',
        'int32',
        'uint32',
        'float32',
        'float64',
        'email',
        'url',
        'uuid',
        'guid',
        'uuidv4',
        'uuidv6',
        'uuidv7',
        'cuid',
        'cuid2',
        'ulid',
        'nanoid',
        'xid',
        'ksuid',
        'emoji',
        'ipv4',
        'ipv6',
        'cidrv4',
        'cidrv6',
        'base64',
        'base64url',
        'e164',
        'jwt',
      ],
      leafWrapperMethods: [
        'optional',
        'nullable',
        'nullish',
        'default',
        'prefault',
        'catch',
        'array',
        'readonly',
        'describe',
      ],
      reuseModifiers: ['optional', 'nullable', 'nullish', 'default', 'unwrap', 'describe'],
      gateway: { brandPrefix: '#Gateway' },
    });
  });
});
