/**
 * PURPOSE: Pass-through for the npm package 'typescript'. Code outside the gateway imports typescript
 * through here instead of the raw package, so a future guard or override on typescript lands in
 * this one file and reaches every caller.
 *
 * typescript's own root declaration is `export = ts;`, and TypeScript hard-refuses `export *`
 * against any `export =`-typed module (`TS2498`, unconditional). A consumer's tsc program (web's
 * `module: ESNext`) reaches this file's SOURCE directly, where `import mod = require(...);
 * export = mod;` is TS1202/TS1203 under that target, so this lists by name every member a caller
 * uses, the way `node/src/path/path.ts` does; plain `export {} from` syntax has no such
 * restriction. A caller that reaches for a member missing here fails typecheck (TS2339) — add the
 * name to the matching list below.
 *
 * USAGE:
 * import * as ts from '#gateway/npm/typescript';
 * import ts from '#gateway/npm/typescript'; // typescript.test.ts pins this to `require('typescript')`
 */

export { default } from 'typescript';
export {
  EmitHint,
  Extension,
  InternalSymbolName,
  JsxEmit,
  ModuleKind,
  ModuleResolutionKind,
  ScriptKind,
  ScriptTarget,
  SyntaxKind,
  TypeFlags,
  addSyntheticLeadingComment,
  canHaveModifiers,
  createCompilerHost,
  createPrinter,
  createProgram,
  createSourceFile,
  factory,
  flattenDiagnosticMessageText,
  forEachChild,
  getDefaultLibFileName,
  getModeForUsageLocation,
  getModifiers,
  getParsedCommandLineOfConfigFile,
  isArrayLiteralExpression,
  isArrowFunction,
  isAwaitExpression,
  isBinaryExpression,
  isBindingElement,
  isBlock,
  isCallExpression,
  isClassDeclaration,
  isConditionalExpression,
  isDoStatement,
  isElementAccessExpression,
  isEnumDeclaration,
  isExportAssignment,
  isExportDeclaration,
  isExpressionStatement,
  isForInStatement,
  isForOfStatement,
  isForStatement,
  isFunctionDeclaration,
  isFunctionExpression,
  isFunctionTypeNode,
  isIdentifier,
  isIdentifierPart,
  isIdentifierStart,
  isIfStatement,
  isImportDeclaration,
  isInterfaceDeclaration,
  isIntersectionTypeNode,
  isMethodSignature,
  isNamedExports,
  isNamedImports,
  isNamespaceExport,
  isNamespaceImport,
  isNewExpression,
  isNonNullExpression,
  isNumericLiteral,
  isObjectLiteralExpression,
  isParameter,
  isParenthesizedExpression,
  isParenthesizedTypeNode,
  isPropertyAccessExpression,
  isPropertyAssignment,
  isPropertySignature,
  isQualifiedName,
  isRegularExpressionLiteral,
  isReturnStatement,
  isShorthandPropertyAssignment,
  isSourceFile,
  isSpreadAssignment,
  isStringLiteral,
  isSwitchStatement,
  isTryStatement,
  isTypeAliasDeclaration,
  isTypeLiteralNode,
  isTypeNode,
  isTypeParameterDeclaration,
  isTypeQueryNode,
  isTypeReferenceNode,
  isVariableDeclaration,
  isVariableStatement,
  isWhileStatement,
  parseJsonText,
  resolveModuleName,
  sys,
} from 'typescript';
export type {
  BindingName,
  CompilerOptions,
  ConciseBody,
  Diagnostic,
  ExportDeclaration,
  Expression,
  Identifier,
  ImportClause,
  ImportDeclaration,
  InterfaceDeclaration,
  MemberName,
  Node,
  NodeFactory,
  ObjectLiteralElementLike,
  ParameterDeclaration,
  ParseConfigFileHost,
  Program,
  PropertyName,
  SourceFile,
  Statement,
  Type,
  TypeAliasDeclaration,
  TypeReference,
  VariableStatement,
} from 'typescript';
