/**
 * PURPOSE: Defines project structure rules and constraints for each folder type
 *
 * USAGE:
 * import { folderConfigStatics } from './statics/folder-config/folder-config-statics';
 * const brokerConfig = folderConfigStatics.brokers;
 * // Returns { fileSuffix: '-broker.ts', exportSuffix: 'Broker', folderDepth: 2, ... }
 *
 * WHEN-TO-USE: When validating file structure or determining expected file naming patterns
 */
export const folderConfigStatics = {
  statics: {
    fileSuffix: '-statics.ts',
    exportSuffix: 'Statics',
    exportCase: 'camelCase',
    folderDepth: 1,
    folderPattern: 'statics/[domain]/[domain]-statics.ts',
    allowedImports: [],
    disallowAdhocTypes: true,
    requireProxy: false,
    allowsLayerFiles: false,
    allowRegex: false,
    meta: {
      purpose:
        'Immutable configuration values and constants. Single source of truth for magic numbers, limits, and unchanging data.',
      whenToUse: 'Need immutable config or constants',
    },
  },
  contracts: {
    fileSuffix: ['-contract.ts', '.stub.ts'],
    exportSuffix: 'Contract',
    exportCase: 'camelCase',
    folderDepth: 1,
    folderPattern: 'contracts/[domain]/[domain]-contract.ts',
    allowedImports: ['statics/', 'errors/', 'contracts/', 'zod', '@dungeonmaster/shared/@types'],
    disallowAdhocTypes: false,
    requireProxy: false,
    allowsLayerFiles: false,
    allowRegex: true,
    meta: {
      purpose:
        'Type definitions and validation schemas using Zod. All data structures must be defined here with branded types.',
      whenToUse: 'Define data structure with validation',
    },
  },
  guards: {
    fileSuffix: '-guard.ts',
    exportSuffix: 'Guard',
    exportCase: 'camelCase',
    folderDepth: 1,
    folderPattern: 'guards/[domain]/[domain]-guard.ts',
    allowedImports: ['contracts/', 'statics/', 'errors/', 'guards/', 'transformers/'],
    disallowAdhocTypes: true,
    requireProxy: false,
    allowsLayerFiles: false,
    allowRegex: true,
    meta: {
      purpose:
        'Pure boolean functions that validate conditions. Return true/false, no side effects.',
      whenToUse: 'Boolean check or type guard',
    },
  },
  transformers: {
    fileSuffix: '-transformer.ts',
    exportSuffix: 'Transformer',
    exportCase: 'camelCase',
    folderDepth: 1,
    folderPattern: 'transformers/[domain]/[domain]-transformer.ts',
    allowedImports: ['contracts/', 'statics/', 'errors/', 'guards/', 'transformers/'],
    disallowAdhocTypes: true,
    requireProxy: false,
    allowsLayerFiles: false,
    allowRegex: true,
    meta: {
      purpose:
        'Pure data transformation functions. Map input types to output types without side effects.',
      whenToUse: 'Transform data shape A to B',
    },
  },
  errors: {
    fileSuffix: '-error.ts',
    exportSuffix: 'Error',
    exportCase: 'PascalCase',
    folderDepth: 1,
    folderPattern: 'errors/[domain]/[domain]-error.ts',
    allowedImports: [],
    disallowAdhocTypes: true,
    requireProxy: false,
    allowsLayerFiles: false,
    allowRegex: false,
    meta: {
      purpose: 'Custom error classes extending Error. Domain-specific error types.',
      whenToUse: 'Custom error with context',
    },
  },
  flows: {
    fileSuffix: ['-flow.ts', '-flow.tsx'],
    exportSuffix: 'Flow',
    exportCase: 'PascalCase',
    folderDepth: 1,
    folderPattern: 'flows/[domain]/[domain]-flow.tsx',
    allowedImports: ['responders/'],
    disallowAdhocTypes: true,
    requireProxy: false,
    allowsLayerFiles: false,
    allowRegex: false,
    meta: {
      purpose:
        'Top-level orchestration components (React) that wire up responders. Entry points for major application flows.',
      whenToUse: 'Define routes or entry points',
    },
  },
  adapters: {
    fileSuffix: '-adapter.ts',
    exportSuffix: 'Adapter',
    exportCase: 'camelCase',
    folderDepth: 2,
    folderPattern: 'adapters/[package]/[operation]/[package]-[operation]-adapter.ts',
    allowedImports: [
      'node_modules',
      'middleware/',
      'statics/',
      'contracts/',
      'guards/',
      '@dungeonmaster/shared/adapters',
    ],
    disallowAdhocTypes: false,
    requireProxy: true,
    allowsLayerFiles: false,
    allowRegex: false,
    meta: {
      purpose:
        'I/O boundary layer translating between external systems and internal contracts. Wrap npm packages, APIs, databases.',
      whenToUse: 'Wrap npm package',
    },
  },
  middleware: {
    fileSuffix: '-middleware.ts',
    exportSuffix: 'Middleware',
    exportCase: 'camelCase',
    folderDepth: 1,
    folderPattern: 'middleware/[name]/[name]-middleware.ts',
    allowedImports: ['adapters/', 'middleware/', 'statics/', 'contracts/', 'guards/'],
    disallowAdhocTypes: true,
    requireProxy: true,
    allowsLayerFiles: false,
    allowRegex: false,
    meta: {
      purpose:
        'Request/response transformation layer. Authentication, logging, validation pipelines.',
      whenToUse: 'Combine adapters for infrastructure',
    },
  },
  brokers: {
    fileSuffix: '-broker.ts',
    exportSuffix: 'Broker',
    exportCase: 'camelCase',
    folderDepth: 2,
    folderPattern: 'brokers/[domain]/[action]/[domain]-[action]-broker.ts',
    allowedImports: [
      'brokers/',
      'adapters/',
      'contracts/',
      'statics/',
      'errors/',
      'guards/',
      'transformers/',
    ],
    disallowAdhocTypes: true,
    requireProxy: true,
    allowsLayerFiles: true,
    allowRegex: false,
    meta: {
      purpose:
        'Business logic orchestration. Compose adapters, guards, transformers to implement domain operations.',
      whenToUse: 'Business logic operations',
    },
  },
  bindings: {
    fileSuffix: '-binding.ts',
    exportSuffix: 'Binding',
    exportCase: 'camelCase',
    folderDepth: 1,
    folderPattern: 'bindings/[name]/[name]-binding.ts',
    allowedImports: [
      'brokers/',
      'state/',
      'contracts/',
      'statics/',
      'errors/',
      'guards/',
      'transformers/',
    ],
    disallowAdhocTypes: true,
    requireProxy: true,
    allowsLayerFiles: false,
    allowRegex: false,
    meta: {
      purpose: 'React hooks that connect widgets to business logic. Bridge between UI and brokers.',
      whenToUse: 'React hook or reactive binding',
    },
  },
  state: {
    fileSuffix: '-state.ts',
    exportSuffix: 'State',
    exportCase: 'camelCase',
    folderDepth: 1,
    folderPattern: 'state/[name]/[name]-state.ts',
    allowedImports: ['contracts/', 'statics/', 'errors/', 'guards/', 'transformers/'],
    disallowAdhocTypes: true,
    requireProxy: true,
    allowsLayerFiles: false,
    allowRegex: false,
    meta: {
      purpose: 'Shared state management. In-memory caches, stores, and state containers.',
      whenToUse: 'In-memory storage',
    },
  },
  responders: {
    fileSuffix: '-responder.ts',
    exportSuffix: 'Responder',
    exportCase: 'PascalCase',
    folderDepth: 2,
    folderPattern: 'responders/[domain]/[action]/[domain]-[action]-responder.ts',
    allowedImports: [
      'widgets/',
      'brokers/',
      'bindings/',
      'state/',
      'contracts/',
      'transformers/',
      'guards/',
      'statics/',
      'errors/',
    ],
    disallowAdhocTypes: true,
    requireProxy: true,
    allowsLayerFiles: true,
    allowRegex: false,
    meta: {
      purpose:
        'Request handlers that orchestrate brokers and bindings. Process incoming requests and return responses.',
      whenToUse: 'Handle HTTP/API requests',
    },
  },
  widgets: {
    fileSuffix: ['-widget.tsx', '-widget.ts'],
    exportSuffix: 'Widget',
    exportCase: 'PascalCase',
    folderDepth: 1,
    folderPattern: 'widgets/[name]/[name]-widget.tsx',
    allowedImports: [
      'bindings/',
      'brokers/',
      'state/',
      'contracts/',
      'transformers/',
      'guards/',
      'statics/',
      'errors/',
    ],
    disallowAdhocTypes: false,
    requireProxy: true,
    allowsLayerFiles: true,
    allowRegex: false,
    meta: {
      purpose: 'React UI components. Visual representation and user interaction.',
      whenToUse: 'UI component or React widget',
    },
  },
  startup: {
    fileSuffix: '.ts',
    exportSuffix: '', // Optional - 0 or 1 exports allowed, if present must be PascalCase
    exportCase: 'PascalCase',
    folderDepth: 0,
    folderPattern: 'startup/start-[name].ts',
    allowedImports: ['*'],
    disallowAdhocTypes: true,
    requireProxy: false,
    allowsLayerFiles: false,
    allowRegex: false,
    meta: {
      purpose:
        'Application initialization and configuration. Entry points, server startup, CLI commands.',
      whenToUse: 'App initialization',
    },
  },
  assets: {
    fileSuffix: '',
    exportSuffix: '',
    exportCase: '',
    folderDepth: 1,
    folderPattern: 'assets/[type]/[filename]',
    allowedImports: [],
    disallowAdhocTypes: true,
    requireProxy: false,
    allowsLayerFiles: false,
    allowRegex: false,
    meta: {
      purpose: 'Static files like images, fonts, and other non-code resources.',
      whenToUse: 'Static files (images, fonts)',
    },
  },
  migrations: {
    fileSuffix: '',
    exportSuffix: '',
    exportCase: '',
    folderDepth: 1,
    folderPattern: 'migrations/[version]/[number]-[name].sql',
    allowedImports: [],
    disallowAdhocTypes: true,
    requireProxy: false,
    allowsLayerFiles: false,
    allowRegex: false,
    meta: {
      purpose: 'Database schema changes and data migrations. Versioned SQL scripts.',
      whenToUse: 'Database or schema upgrades',
    },
  },
} as const;
