import { folderConfigStatics } from './folder-config-statics';

describe('folderConfigStatics', () => {
  it('VALID: exported value => matches expected shape', () => {
    expect(folderConfigStatics).toStrictEqual({
      statics: {
        fileSuffix: '-statics.ts',
        exportSuffix: 'Statics',
        exportCase: 'camelCase',
        folderDepth: 1,
        folderPattern: 'statics/[domain]/[domain]-statics.ts',
        allowedImports: ['statics/'],
        disallowAdhocTypes: true,
        requireProxy: false,
        allowsLayerFiles: true,
        allowRegex: true,
        requireContractDeclarations: false,
        testType: 'unit',
        requireStub: false,
        meta: {
          purpose:
            'Immutable configuration values and constants. Single source of truth for magic numbers, limits, and unchanging data.',
          whenToUse: 'Need immutable config or constants',
        },
      },
      contracts: {
        fileSuffix: ['-contract.ts', '.stub.ts'],
        exportSuffix: 'Contract',
        exportCase: 'camelCase',
        folderDepth: 1,
        folderPattern: 'contracts/[domain]/[domain]-contract.ts',
        allowedImports: [
          'statics/',
          'errors/',
          'contracts/',
          '#gateway/npm/zod',
          '@dungeonmaster/shared/@types',
          '@dungeonmaster/orchestrator',
        ],
        disallowAdhocTypes: false,
        requireProxy: false,
        allowsLayerFiles: true,
        allowRegex: true,
        requireContractDeclarations: false,
        testType: 'unit',
        requireStub: true,
        meta: {
          purpose:
            'Type definitions and validation schemas for the data we define. Every object and every field in it is branded.',
          whenToUse: 'Define data structure with validation',
        },
      },
      guards: {
        fileSuffix: '-guard.ts',
        exportSuffix: 'Guard',
        exportCase: 'camelCase',
        folderDepth: 1,
        folderPattern: 'guards/[domain]/[domain]-guard.ts',
        allowedImports: ['contracts/', 'statics/', 'errors/', 'guards/', 'transformers/'],
        disallowAdhocTypes: true,
        requireProxy: false,
        allowsLayerFiles: false,
        allowRegex: true,
        requireContractDeclarations: true,
        testType: 'unit',
        requireStub: false,
        meta: {
          purpose:
            'Pure boolean functions that validate conditions. Return true/false, no side effects.',
          whenToUse: 'Boolean check or type guard',
        },
      },
      transformers: {
        fileSuffix: '-transformer.ts',
        exportSuffix: 'Transformer',
        exportCase: 'camelCase',
        folderDepth: 1,
        folderPattern: 'transformers/[domain]/[domain]-transformer.ts',
        allowedImports: ['contracts/', 'statics/', 'errors/', 'guards/', 'transformers/'],
        disallowAdhocTypes: true,
        requireProxy: false,
        allowsLayerFiles: true,
        allowRegex: true,
        requireContractDeclarations: true,
        testType: 'unit',
        requireStub: false,
        meta: {
          purpose:
            'Pure data transformation functions. Map input types to output types without side effects.',
          whenToUse: 'Transform data shape A to B',
        },
      },
      errors: {
        fileSuffix: '-error.ts',
        exportSuffix: 'Error',
        exportCase: 'PascalCase',
        folderDepth: 1,
        folderPattern: 'errors/[domain]/[domain]-error.ts',
        allowedImports: [],
        disallowAdhocTypes: true,
        requireProxy: false,
        allowsLayerFiles: false,
        allowRegex: false,
        requireContractDeclarations: true,
        testType: 'unit',
        requireStub: false,
        meta: {
          purpose: 'Custom error classes extending Error. Domain-specific error types.',
          whenToUse: 'Custom error with context',
        },
      },
      flows: {
        fileSuffix: ['-flow.ts', '-flow.tsx'],
        exportSuffix: 'Flow',
        exportCase: 'PascalCase',
        folderDepth: 1,
        folderPattern: 'flows/[domain]/[domain]-flow.tsx',
        allowedImports: [
          'contracts/',
          'transformers/',
          'guards/',
          'statics/',
          'errors/',
          'flows/',
          'responders/',
          '#gateway/npm/hono',
          '#gateway/npm/react-router-dom',
          '#gateway/npm/express',
          '#gateway/npm/modelcontextprotocol__sdk',
          '#gateway/npm/zod-to-json-schema',
        ],
        disallowAdhocTypes: true,
        requireProxy: false,
        allowsLayerFiles: true,
        allowRegex: false,
        requireContractDeclarations: true,
        testType: 'integration',
        requireStub: false,
        meta: {
          purpose:
            'Top-level orchestration components (React) that wire up responders. One flow file per entry point — a route, a command, a subcommand — with the domain-level file routing to a layer flow per entry point rather than wiring every entry point inline.',
          whenToUse:
            'Define a route or entry point; one file per entry point, routed through a layer flow',
        },
      },
      middleware: {
        fileSuffix: '-middleware.ts',
        exportSuffix: 'Middleware',
        exportCase: 'camelCase',
        folderDepth: 1,
        folderPattern: 'middleware/[name]/[name]-middleware.ts',
        allowedImports: ['middleware/', 'statics/', 'contracts/', 'guards/', 'transformers/'],
        disallowAdhocTypes: true,
        requireProxy: true,
        allowsLayerFiles: false,
        allowRegex: false,
        requireContractDeclarations: true,
        testType: 'unit',
        requireStub: false,
        meta: {
          purpose:
            'Combines two or more gateway wrappers into one infrastructure concern, such as a render wrapper or a package.json read.',
          whenToUse: 'Combine gateway wrappers for infrastructure',
        },
      },
      brokers: {
        fileSuffix: '-broker.ts',
        exportSuffix: 'Broker',
        exportCase: 'camelCase',
        folderDepth: 2,
        folderPattern: 'brokers/[domain]/[action]/[domain]-[action]-broker.ts',
        allowedImports: [
          'brokers/',
          'contracts/',
          'statics/',
          'errors/',
          'guards/',
          'transformers/',
          '@dungeonmaster/orchestrator',
        ],
        disallowAdhocTypes: true,
        requireProxy: true,
        allowsLayerFiles: true,
        allowRegex: false,
        requireContractDeclarations: true,
        testType: 'unit',
        requireStub: false,
        meta: {
          purpose:
            'Business logic orchestration. Compose gateway wrappers, guards, transformers to implement domain operations.',
          whenToUse: 'Business logic operations',
        },
      },
      bindings: {
        fileSuffix: '-binding.ts',
        exportSuffix: 'Binding',
        exportCase: 'camelCase',
        folderDepth: 1,
        folderPattern: 'bindings/[name]/[name]-binding.ts',
        allowedImports: [
          'brokers/',
          'state/',
          'contracts/',
          'statics/',
          'errors/',
          'guards/',
          'transformers/',
          '#gateway/npm/react',
          '@dungeonmaster/orchestrator',
        ],
        disallowAdhocTypes: true,
        requireProxy: true,
        allowsLayerFiles: true,
        allowRegex: false,
        requireContractDeclarations: true,
        testType: 'unit',
        requireStub: false,
        meta: {
          purpose:
            'React hooks that connect widgets to business logic. Bridge between UI and brokers.',
          whenToUse: 'React hook or reactive binding',
        },
      },
      state: {
        fileSuffix: '-state.ts',
        exportSuffix: 'State',
        exportCase: 'camelCase',
        folderDepth: 1,
        folderPattern: 'state/[name]/[name]-state.ts',
        allowedImports: ['contracts/', 'statics/', 'errors/', 'guards/', 'transformers/'],
        disallowAdhocTypes: true,
        requireProxy: true,
        allowsLayerFiles: false,
        allowRegex: false,
        requireContractDeclarations: true,
        testType: 'unit',
        requireStub: false,
        meta: {
          purpose: 'Shared state management. In-memory caches, stores, and state containers.',
          whenToUse: 'In-memory storage',
        },
      },
      responders: {
        fileSuffix: '-responder.ts',
        exportSuffix: 'Responder',
        exportCase: 'PascalCase',
        folderDepth: 2,
        folderPattern: 'responders/[domain]/[action]/[domain]-[action]-responder.ts',
        allowedImports: [
          'widgets/',
          'brokers/',
          'bindings/',
          'state/',
          'contracts/',
          'transformers/',
          'guards/',
          'statics/',
          'errors/',
          '@dungeonmaster/orchestrator',
        ],
        disallowAdhocTypes: true,
        requireProxy: true,
        allowsLayerFiles: true,
        allowRegex: false,
        requireContractDeclarations: true,
        testType: 'unit',
        requireStub: false,
        meta: {
          purpose:
            'Request handlers that orchestrate brokers and bindings. Process incoming requests and return responses.',
          whenToUse: 'Handle HTTP/API requests',
        },
      },
      widgets: {
        fileSuffix: ['-widget.tsx', '-widget.ts'],
        exportSuffix: 'Widget',
        exportCase: 'PascalCase',
        folderDepth: 1,
        folderPattern: 'widgets/[name]/[name]-widget.tsx',
        allowedImports: [
          'bindings/',
          'brokers/',
          'state/',
          'contracts/',
          'transformers/',
          'guards/',
          'statics/',
          'errors/',
          'widgets/',
          '#gateway/npm/react',
          '#gateway/npm/mantine__core',
          '#gateway/npm/mantine__hooks',
          '#gateway/npm/ansi-to-react',
          '#gateway/npm/react-router-dom',
          '#gateway/npm/tabler__icons-react',
          '#gateway/npm/testing-library__react',
          '#gateway/npm/testing-library__user-event',
        ],
        disallowAdhocTypes: false,
        requireProxy: true,
        allowsLayerFiles: true,
        allowRegex: false,
        requireContractDeclarations: true,
        testType: 'unit',
        requireStub: false,
        meta: {
          purpose: 'React UI components. Visual representation and user interaction.',
          whenToUse: 'UI component or React widget',
        },
      },
      startup: {
        fileSuffix: '.ts',
        exportSuffix: '',
        exportCase: 'PascalCase',
        folderDepth: 0,
        folderPattern: 'startup/start-[name].ts',
        allowedImports: ['flows/', 'contracts/', 'statics/', 'errors/'],
        disallowAdhocTypes: true,
        requireProxy: false,
        allowsLayerFiles: false,
        allowRegex: false,
        requireContractDeclarations: true,
        testType: 'integration',
        requireStub: false,
        meta: {
          purpose:
            'Application initialization and configuration. Entry points, server startup, CLI commands.',
          whenToUse: 'App initialization',
        },
      },
      assets: {
        fileSuffix: '',
        exportSuffix: '',
        exportCase: '',
        folderDepth: 1,
        folderPattern: 'assets/[type]/[filename]',
        allowedImports: [],
        disallowAdhocTypes: true,
        requireProxy: false,
        allowsLayerFiles: false,
        allowRegex: false,
        requireContractDeclarations: false,
        testType: 'none',
        requireStub: false,
        meta: {
          purpose: 'Static files like images, fonts, and other non-code resources.',
          whenToUse: 'Static files (images, fonts)',
        },
      },
      migrations: {
        fileSuffix: '',
        exportSuffix: '',
        exportCase: '',
        folderDepth: 1,
        folderPattern: 'migrations/[version]/[number]-[name].sql',
        allowedImports: [],
        disallowAdhocTypes: true,
        requireProxy: false,
        allowsLayerFiles: false,
        allowRegex: false,
        requireContractDeclarations: true,
        testType: 'none',
        requireStub: false,
        meta: {
          purpose: 'Database schema changes and data migrations. Versioned SQL scripts.',
          whenToUse: 'Database or schema upgrades',
        },
      },
    });
  });
});
